OpenDevicePartnership/embedded-services

- hid-service/src/i2c/passthrough/mod.rs
Update info message to display the actually ID and not the debug wrapper.
> hid-service/passthrough: Fix device ID formatting

- .github/workflows/check.yml
- embedded-service/src/fmt.rs
- power-button-service/Cargo.toml
Split up logging macros implementations along feature lines. Using these macros as is in dependent crates can leak the `defmt` and `log` features resulting in warnings if it only supports one of the features.
> embedded-service: refactor logging macros

- .github/workflows/check.yml
These features are mutally exclusive in embassy so run docs on both.
> workflows: Update cargo doc invocations to not enable both defmt and log

- .github/workflows/check.yml
- .github/workflows/nostd.yml
- storage-bus/Cargo.toml
- storage-bus/README.md
- storage-bus/src/lib.rs
- storage-bus/src/nand.rs
- storage-bus/src/nor.rs
This PR adds generic storage bus traits to be used by the NOR flash device drivers. Device drivers can use the traits to access the lower level storage busses like FlexSPI, SPI, etc.
PR also adds traits for NAND storage bus for future support
> Adding storage bus traits

- .github/workflows/check.yml
- README.md
- cfu-service/Cargo.toml
- cfu-service/src/host.rs
- cfu-service/src/lib.rs
- embedded-service/Cargo.toml
- embedded-service/src/cfu/component.rs
- embedded-service/src/cfu/mod.rs
- embedded-service/src/lib.rs
- examples/std/Cargo.toml
- examples/std/src/bin/cfu_client.rs
Defines a Cfu Client service crate, integrates the necessary hooks in the embedded-service crate, and creates an example for a cfu-client.
This PR also stubs out a Cfu host service based on the host traits from the pulled in embedded-cfu-protocol crate. Most EC's will be clients and not hosts for CFU offers.
> Cfu Service

- embedded-service/src/comms.rs
- embedded-service/src/ec_type/message.rs
- embedded-service/src/ec_type/mod.rs
- embedded-service/src/ec_type/structure.rs
- espi-service/src/espi_service.rs
Implement peripheral channel write support for eSPI service. On host writes to battery, thermal, and time alarm section of the EC memory map, a message will be generated to be forwarded to the underlying service with the updated.
Going through the fields in each section, it does not seem like host would update some of them. But for now, forward any writes to the service for now. Later on with more input from subsystem teams, we can remove the forwarding for fields that should never be updated by the host.
Closes #181
> Add peripheral channel write support to eSPI service

- embedded-service/src/ec_type/generator/ec-memory-generator.py
- embedded-service/src/ec_type/generator/ec_memory_map.yaml
- embedded-service/src/ec_type/structure.rs
- espi-service/src/espi_service.rs
- Add EC memory layout YAML file to source control
- Add Python generator to generate both C and Rust header files for the EC memory layout
- Update the EC memory layout to the latest generated from YAML file
- Version the EC memory layout as 0.1.0
- Update eSPI service to set the version on initialization
> Update eSPI memory map layout to the latest and version it as 0.1.0

- espi-service/Cargo.toml
- espi-service/src/espi_service.rs
- examples/rt633/Cargo.toml
- examples/rt685s-evk/Cargo.toml
- Fix breakage due to embassy-imxrt
- Lock embassy-imxrt to a commit to avoid accidental breakage in the future
- https://github.com/OpenDevicePartnership/embassy-imxrt/commit/35d430666574379ef2186c25172ca848ae19d11b
> espi-service: update due to imxrt breakage

- cfu-service/Cargo.toml
- embedded-service/src/ec_type/generator/ec-memory-generator.py
- embedded-service/src/ec_type/message.rs
- embedded-service/src/ec_type/mod.rs
- embedded-service/src/ec_type/structure.rs
Due to previous broken workflows, missed a few things.
- Fix clippy warning due to not documented version construct
- Fix unit test due to updated battery struct
- Fix missing license field in Cargo.toml
> Fix unit test failure and clippy warning

- examples/rt685s-evk/src/bin/type_c.rs
A config option was recently added to the power policy, update this example.
> examples/rt685s-evk/type-c: Add missing power policy config argument

- embedded-service/src/type_c/comms.rs
- embedded-service/src/type_c/mod.rs
- examples/rt685s-evk/src/bin/type_c.rs
- examples/std/Cargo.lock
- examples/std/src/bin/type_c/service.rs
- type-c-service/src/task.rs
Adds support for debug accessory connect/disconnect and broadcast a message in response. This is currently on top of https://github.com/OpenDevicePartnership/embedded-services/pull/122 while that is in review. Please start with commit 6470bcee9ef012651c19078fa6f12310f7e2c5b1 for now.
> Type-C debug accessory support

- embedded-service/src/cfu/component.rs
In the implementation of CfuWriter for CfuComponentDefault, fixes the cfu_read function to call the internal cfu_read instead of cfu_write
> Fix cfu_read wrapper's internal call

- Cargo.lock
- embedded-service/src/lib.rs
- embedded-service/src/type_c/controller.rs
- embedded-service/src/type_c/external.rs
- embedded-service/src/type_c/mod.rs
- examples/std/Cargo.toml
- examples/std/src/bin/type_c/external.rs
- type-c-service/src/task.rs
This PR creates the framework required for the type-C service to respond to external commands. Full functionality will be added by subsequent PRs. Closes #215
> Type-C: Setup framework for handling external commands

- .github/workflows/check.yml
- supply-chain/README.md
- supply-chain/audits.toml
- supply-chain/config.toml
- supply-chain/imports.lock
Initializing cargo vet for this repository. This allows us to audit the third party dependencies being used in the code.
As part of initialization, all current dependencies are under exemptions. These need to be audited as time permits.
We import audits from Mozilla and Google. Dependencies that have been already audited by either of them are added to imports.lock file by cargo vet
A new workflow is also being added to run cargo vet on any new PR
Closes #210
> Cargo vet init

- Cargo.toml
- examples/rt685s-evk/Cargo.toml
- examples/rt685s-evk/src/bin/nvram.rs
- platform-service/Cargo.toml
- platform-service/src/imxrt/mod.rs
- platform-service/src/lib.rs
- platform-service/src/nvram.rs
Adds a preliminary platform services crate for managing and abstracting common mechanisms like NVRAM without imposing knowledge of underlying implementer on users of said features.
Has a temporary work around for missing GPREG management APIs in embassy-imxrt
> Add Basic NVRAM Platform Service Abstraction

- .github/workflows/check.yml
- .github/workflows/nostd.yml
- Cargo.lock
Since we're checking in cargo.lock into the repo, it is expected that it builds with the dependencies listed in the lock file.
Updating GitHub workflows to use the locked dependencies ensures that the build is reproducible.
Also updating the lock file to include the platform-service dependency.
> Update actions to use locked dependencies

- supply-chain/config.toml
`cargo vet` is primarily to audit third party dependencies from crates.io
Since embassy crates are also published on crates.io but we're using the GitHub versions, this leads to some issues.
If we mark them to have the same audit criteria as applied to other crates `audit-as-crates-io = true`, it would mean that we need to audit new versions of the dependencies every time cargo.lock is updated, which is pretty frequent for a GitHub based dependency as it uses the commit hash of the HEAD.
If we don't include them in config.toml, it results in a vet failure as matches are found on crates.io, but they don't match with what we're using.
The alternative is to mark them as not from crates.io, which is what this PR does.
We mark them as `audit-as-crates-io = false`, which is meant to be used for …
> Avoid vetting embassy dependencies pulled from GitHub

- type-c-service/src/driver/tps6699x.rs
These periodic `INFO` logs show up approximately every second but aren't paticularly useful for most developers, only those actively working on the type-c service. As such, reducing their log levels and recommending developers use defmt's log filtering is more appropriate.
> Reduce log spam from type-c service

- power-policy-service/src/charger.rs
Currently, the charger wrapper consumes the device object when the wrapper is instantiated.
However, when we register the charger device with the power-policy service, we pass it a static reference. Thus, the device needs to be statically allocated and therefore must not be consumed by the wrapper.
This change changes the wrapper to hold the device by reference instead.
> Pass charger device by reference to charger wrapper

- examples/std/Cargo.lock
- examples/std/Cargo.toml
Our standard examples are failing to link, probably due to some upstream crate removing a dependency for a standard critical section. This change adds a dependency to the `critical-section` crate with the `std` feature to fix the link error.
> Add critical-section crate to std examples

- deny.toml
Mirror of https://github.com/OpenDevicePartnership/embassy-imxrt/pull/408, but for embedded-services
> Temporarily suppress deprecation warning for RUSTSEC-2023-0089

- examples/rt685s-evk/src/bin/type_c.rs
Fixes broken example and broken CI
> type-c example: Pass in interrupts by slice rather than array

- platform-service/src/embedded_crc.rs
Improve code quality by using cfg_attr flag for defmt feature on EmbeddedCrcError instead of creating two types
> Config attribute for defmt feature on EmbeddedCrcError

- Cargo.lock
- examples/rt633/Cargo.lock
- examples/rt685s-evk/Cargo.lock
- examples/rt685s-evk/src/bin/reset.rs
- platform-service/Cargo.toml
- platform-service/src/lib.rs
- platform-service/src/reset.rs
Add an equivalent to NVIC_SystemReset(), that allows registration of pre-emptive blockers that can temporarily hold off the MCU platform reset.
> Add Platform Reset Service

- Cargo.lock
- examples/std/Cargo.lock
- type-c-service/src/driver/tps6699x.rs
When the controller is running FW with autofet enabled, commands related to sink control will be rejected. Normally this should be an error, but we're going to temporarily ignore this failure to allow existing devices to update to FW with autofet disabled without fear of getting stuck in a dead battery state.
> type-c-service/tps6699x: Add workaround for autofet sink rejection

- embedded-service/src/buffer.rs
- embedded-service/src/comms.rs
- embedded-service/src/fmt.rs
- embedded-service/src/hid/command.rs
- embedded-service/src/hid/mod.rs
- embedded-service/src/intrusive_list.rs
- embedded-service/src/power/mod.rs
- embedded-service/src/power/policy/action/device.rs
- embedded-service/src/power/policy/action/policy.rs
- embedded-service/src/power/policy/device.rs
- embedded-service/src/power/policy/policy.rs
- embedded-service/src/type_c/controller.rs
- espi-service/src/espi_service.rs
- hid-service/src/i2c/device.rs
- hid-service/src/i2c/host.rs
- hid-service/src/i2c/passthrough/interrupt.rs
- power-policy-service/src/provider.rs
- type-c-service/src/driver/tps6699x.rs
This PR addresses all `cargo clippy` warnings.
Resolves #247
> Fix cargo clippy warnings

- type-c-service/src/driver/tps6699x.rs
This macro was previously unused and got removed as part of a general clean-up just as a commit that used it landed. Add it back in to fix the build breaking.
> type-c-service/tps6699x: Add `info` import

- power-policy-service/src/consumer.rs
FYI @sukomath @asasine @RobertZ2011 
Add timeout as a temporary quick fix to charger data race bug.
Will be reverted once a proper fix is in later this week.
> Add timeout before updating charger settings and after connecting new power policy consumer

- embedded-service/src/type_c/controller.rs
- examples/std/src/bin/type_c/service.rs
- type-c-service/src/driver/tps6699x.rs
- type-c-service/src/wrapper/mod.rs
Add a function to sync the state of the controller and its ports. If a charger is plugged in before reset then there won't be any interrupts to inform the EC that anything is connected. Add a function to sync the software state of the controller with the hardware state.
> type-c: Add function to sync controller state

- docs/power-policy.md
- embedded-service/src/power/policy/action/device.rs
- embedded-service/src/power/policy/action/policy.rs
- embedded-service/src/power/policy/device.rs
- examples/std/src/bin/power_policy.rs
- power-policy-service/src/config.rs
- power-policy-service/src/lib.rs
- power-policy-service/src/provider.rs
- type-c-service/src/wrapper/mod.rs
- type-c-service/src/wrapper/power.rs
Remove logic to automatically upgrade a provider contract if power is available. This can result in a device receiving more power than needed while another device receives less. This is particularly a concern for TBT compliance testing. With this change devices will have to explicitly request a higher contract. This also removes the recovery logic which was only used in cases where we attempted to downgrade a contract. The new behavior does not attempt to downgrade contracts, so it's no longer needed.
> power-policy: Remove automatic provider upgrade logic

- Cargo.lock
- embedded-service/src/power/policy/mod.rs
- embedded-service/src/type_c/controller.rs
- examples/rt685s-evk/Cargo.lock
- examples/rt685s-evk/Cargo.toml
- examples/rt685s-evk/src/bin/type_c_cfu.rs
- examples/std/Cargo.lock
- examples/std/src/bin/type_c/service.rs
- type-c-service/Cargo.toml
- type-c-service/src/driver/tps6699x.rs
- type-c-service/src/wrapper/cfu.rs
- type-c-service/src/wrapper/mod.rs
- type-c-service/src/wrapper/pd.rs
- type-c-service/src/wrapper/power.rs
This PR adds CFU support directly integrated within the existing type-C code. This is meant to get this functionality in for the moment while work on more general FW update support continues.
> type-c-service: Add integrated CFU support

- embedded-service/src/power/policy/charger.rs
- embedded-service/src/power/policy/mod.rs
- embedded-service/src/power/policy/policy.rs
- power-policy-service/src/charger.rs
- power-policy-service/src/consumer.rs
Changelog:
- added Powered and Unpowered states
- **Breaking Change** this change is made because an unpowered state is a valid state the charger can be in, specifically in dead battery scenarios where the charger power rail might not be turned on. Power-policy's `connect_new_consumer()` relies on being able to communicate with the charger but the charger needs to be powered, which doesn't happen until later in the function.
- added Check Ready command to transition from Unpowered to Powered state and vice-versa
- **Breaking Change**
- Renamed ChargeController::BusError to ChargeControllerError and added a trait bound to impl From for charger::ChargerError
- **Breaking change** but I believe this is needed since, with the more constrained need to convert the custom error type to a …
> Power Policy Charger Updates

- power-policy-service/src/consumer.rs
Changes in #349 got incorrectly moved around in #329. Fix by adding unpowered check back to idle policy.
> Add charger unpowered check to idle Policy

- embedded-service/src/activity.rs
- embedded-service/src/intrusive_list.rs
- embedded-service/src/lib.rs
- embedded-service/src/sync_cell.rs
Embassy upstream recently fixed accidentally adding Sync to non-Sync types: https://github.com/embassy-rs/embassy/pull/4320
In preparation to fix #361, added a drop-in replacement for Cell where moving to a proper primitive usage such as embassy_sync::mutex::Mutex is untenable. This also refactors the intrusive_list to utilize this new SyncCell type, allowing it to be used directly without any containers.
Note that in most cases SyncCell is not the best solution. If it is possible, proper synchronization primitives should be leveraged.
A critical section was used as opposed to a blocking_mutex type, as blocking_mutex is non-re-entrant. This allows the most flexibility in supporting scenarios with SyncCell, and does not require permutated get and set implementations based on mutex backing …
> Add SyncCell type to support Sync fix in embassy upstream

- embedded-service/src/type_c/controller.rs
- embedded-service/src/type_c/external.rs
- examples/rt685s-evk/src/bin/type_c.rs
- examples/std/src/bin/type_c/basic.rs
- type-c-service/src/task.rs
- type-c-service/src/wrapper/mod.rs
- type-c-service/src/wrapper/pd.rs
PD controllers may maintain power and state independently of the EC. If
a port was attached prior to an EC reset then the PD controller might
not trigger an interrupt since nothing has changed on its end. Add a way
to force a sync of the PD controller state to handle this situation.
> type-c-service: Move controller sync state functionality to external API

- battery-service/src/context.rs
- battery-service/src/controller.rs
- battery-service/src/lib.rs
- battery-service/src/wrapper.rs
Changelog:
- add config to battery service context, allowing OEMs to tweak the inner workings of the battery service. More config features are planned as the state machine matures and locks down
- Add the ability to asynchronously query the state of the battery service
- as a result, state is now a `Mutex` instead of a `RefCell`
- Remove state machine autonomously progressing through the states, meaning now the state machine needs to be explicitly sent commands to drive the state machine from one state to the next.
> Battery service: add context config, async state getter, and remove autonomous state machine logic

- type-c-service/src/wrapper/mod.rs
- type-c-service/src/wrapper/power.rs
Previously, we sent `SRDY` when we received a new consumer contract, but this may fail if PD controller isn't ready to sink power from the provider. The controller indicates this with the Sink Ready interrupt, which is fired when an explicit or implicit contract has been established. As such, Sink Ready always implies a contract is available, and `type_c_service::driver::tps6699x::Tps6699x::update_port_status()` ensures that `PortStatus::available_sink_contract` is valid by the time that `type_c_service::wrapper::ControllerWrapper::process_event()` is called.
Now, we only notify power policy of the new sink contract after the Sink Ready interrupt. In turn, that notification becomes a request to send `SRDY` to the PD controller.
Fixes #338 
Also fixes a bug where we were incorrectly …
> Only send `SRDY` after Sink Ready interrupt

- embedded-service/src/intrusive_list.rs
- embedded-service/src/power/policy/device.rs
- embedded-service/src/power/policy/mod.rs
- embedded-service/src/power/policy/policy.rs
- embedded-service/src/sync_cell.rs
- embedded-service/src/type_c/controller.rs
- examples/std/src/bin/battery.rs
- examples/std/src/bin/buffer.rs
- examples/std/src/bin/cfu_buffer.rs
- examples/std/src/bin/cfu_client.rs
- examples/std/src/bin/cfu_splitter.rs
- examples/std/src/bin/power_policy.rs
- examples/std/src/bin/type_c/basic.rs
- examples/std/src/bin/type_c/external.rs
- examples/std/src/bin/type_c/service.rs
- power-policy-service/src/consumer.rs
Running `cargo +beta clippy` revealed several more clippy warnings. The original intention of our clippy CI workflow was to take these into account since beta features will become stable in the future and this helps us stay ahead of the curve.
> Fix +beta clippy warnings

- .github/workflows/check.yml
Updates the GitHub workflow to ensure clippy warnings cause the workflow to fail.
The explicit `clippy` job (which was nonfunctional and relied on `giraffate/clippy-action`) has been removed since we weren't using reviewdog to post reviews and thus had limited use. Instead, `check` in `cargo hack` was replaced with `clippy` to ensure we check all feature combinations. Similarly, examples were changed to use `clippy` instead of `check` as well.
Lastly, the `test` job also includes checking for clippy warnings on tests.
The repo settings will also likely need to be changed as it seems to be stuck waiting on jobs that no longer exist.
Depends on #360 getting merged (which I'll then rebase on) in order for the new checks to pass.
> Fix clippy workflow

- Cargo.toml
There was a breaking change and minor version update (0.2.0) in embedded-cfu via https://github.com/OpenDevicePartnership/embedded-cfu/pull/21. While the necessary changes are integrated, limit version to 0.1.0 for the workspace in cargo.toml
> Add version limit to embedded-cfu-protocol import after breaking change

- battery-service/src/context.rs
Dynamic and static data requests are designed to be queried frequently, thus `info!()` prints are much too high of a log level. Reduce to `trace!()`
> Quiet down battery state machine prints when collecting dynamic and static data

- cfu-service/src/buffer.rs
- cfu-service/src/lib.rs
- cfu-service/src/splitter.rs
- embedded-service/src/cfu/component.rs
- examples/std/src/bin/cfu_buffer.rs
- examples/std/src/bin/cfu_splitter.rs
- type-c-service/src/wrapper/cfu.rs
* Introduce request data variants for extended and information offers
* Add more logging around buffering CFU requests
> cfu-service: Thread through extended offer requests

- embedded-service/src/lib.rs
- embedded-service/src/transformers/mod.rs
- embedded-service/src/transformers/object.rs
- examples/std/src/bin/type_c/service.rs
- type-c-service/src/wrapper/mod.rs
Our existing wrapper structs don't provide a way to access the actual device object. This makes implementing custom functionality almost impossible. Create `Object` trait that wrappers can implement to grant access to the underlying device. Also implement this trait for the type-C controller wrapper and update the type-c-service example to demonstrate this functionality.
> transformers: Create `Object` trait

- embedded-service/src/power/policy/action/device.rs
- embedded-service/src/power/policy/action/policy.rs
- embedded-service/src/power/policy/device.rs
- embedded-service/src/power/policy/flags.rs
- embedded-service/src/power/policy/mod.rs
- embedded-service/src/power/policy/policy.rs
- examples/std/src/bin/power_policy.rs
- power-policy-service/src/consumer.rs
- power-policy-service/src/lib.rs
- power-policy-service/src/provider.rs
- type-c-service/src/wrapper/power.rs
* Add consumer and provider flags to allow signaling more info to policy without needing future breaking changes
* Implement logic to prioritize unconstrained devices
> power-policy: Add unconstrained logic

- type-c-service/src/lib.rs
The module needs to be public to access types like `Service` to implement OEM-specific event loops.
> Make `type_c_service::task` module public

- .github/workflows/check.yml
Our code base now builds differently based on target (e.g. `std/x86_64-unknown-linux-gnu` vs `thumbv8m.main-none-eabihf`).
For example if targeting std, `CriticalSectionCell` is built, and if not, `ThreadModeCell` is built.
Our original workflow only checked the default (`x86_64-unknown-linux-gnu`) target, which led to a PR making it past that failed MSRV check since it included code only built when target is `thumbv8m.main-none-eabihf`, but that code wasn't stable under 1.85 (see #404).
This PR ensures the MSRV job analyzes both targets (and additionally the clippy jobs as well).
The test job remains unchanged since that should always run under `std`, and likewise the examples jobs are unchanged as those explicitly mention their targets.
> Add target check to workflow

- embedded-service/src/power/policy/mod.rs
- examples/rt685s-evk/src/bin/type_c.rs
- examples/std/src/bin/power_policy.rs
- power-policy-service/src/consumer.rs
- power-policy-service/src/lib.rs
Keep track of unconstrained state and broadcast relevant event.
> power-policy-service: Keep track of policy unconstrained state

- examples/rt633/Cargo.lock
- examples/rt633/src/bin/espi.rs
This PR updates the dependencies of `examples/rt633` and fixes a breakage that causes (which was causing our rolling workflow to fail).
> Update rt633 example dependencies and fix breakage

- embedded-service/src/power/policy/mod.rs
- embedded-service/src/power/policy/policy.rs
- examples/std/src/bin/power_policy.rs
- power-policy-service/src/lib.rs
This provides a more general way to receive events than the comms service.
> power-policy: Broadcast events

- Cargo.lock
- embedded-service/src/type_c/controller.rs
- embedded-service/src/type_c/event.rs
- examples/rt685s-evk/src/bin/type_c.rs
- examples/rt685s-evk/src/bin/type_c_cfu.rs
- examples/std/src/bin/type_c/service.rs
- type-c-service/Cargo.toml
- type-c-service/src/driver/tps6699x.rs
- type-c-service/src/lib.rs
- type-c-service/src/task.rs
- type-c-service/src/wrapper/cfu.rs
- type-c-service/src/wrapper/mod.rs
- type-c-service/src/wrapper/pd.rs
- type-c-service/src/wrapper/power.rs
This PR is a refactoring of the type-C event loop to achieve the following:
* Open up the wrapper event loop to allow for users of the code to control event processing. This moves the wrapper code over to use a stream of port events. This better matches how the type-C service implementation events are.
* Add support for alert/VDM. The existing event bitflags are now split up. The existing port status related flags are in their own portion and the alert and VDM ones are in their own. This is meant to reflect how they're used in code. The status flags are related to port state and are generally handled by the same code paths. While the alert and VDM events are notifications to us that are don't really impact the port state and will be handled by completely different code.
Also increase the …
> Type-c: Event loop refactoring

- type-c-service/src/wrapper/mod.rs
This code was accidentally holding a reference to a variable in a mutex which could block other event processing. Copy the value out of the mutex instead.
> type-c-service: Fix lock that was getting held too long

- Cargo.lock
- Cargo.toml
- examples/std/Cargo.lock
- examples/std/Cargo.toml
- examples/std/src/bin/thermal.rs
- supply-chain/audits.toml
- thermal-service/Cargo.toml
- thermal-service/src/context.rs
- thermal-service/src/fan.rs
- thermal-service/src/lib.rs
- thermal-service/src/mctp.rs
- thermal-service/src/mptf.rs
- thermal-service/src/sensor.rs
- thermal-service/src/utils.rs
This overhauls the first attempt of a thermal service to be more flexible. The thermal service provides:
- Async friendly approach to interfacing with sensors and fans. Each sensor and fan runs in its own task, waiting to receive and process commands and performing additional duties described below.
- Each sensor is responsible for periodically sampling and caching temperature samples to be quickly retrieved when asked.
- Each sensor is responsible for checking if the most recent temperature sample exceeds several thresholds (Warn, Prochot, Critical) and generating an event if so.
- These events can be listened for by OEM to handle appropriately (such as throttling AP in case of Prochot)
- Sensors support various requests such as changing sampling period (to sample more frequently as …
> Implement initial thermal service

- embedded-service/src/cfu/component.rs
- embedded-service/src/ipc/deferred.rs
- embedded-service/src/power/policy/device.rs
- embedded-service/src/type_c/controller.rs
- embedded-service/src/type_c/event.rs
- embedded-service/src/type_c/external.rs
- embedded-service/src/type_c/mod.rs
- examples/rt685s-evk/src/bin/type_c.rs
- examples/rt685s-evk/src/bin/type_c_cfu.rs
- examples/std/Cargo.lock
- examples/std/src/bin/type_c/basic.rs
- examples/std/src/bin/type_c/external.rs
- examples/std/src/bin/type_c/service.rs
- examples/std/src/lib/type_c/mock_controller.rs
- type-c-service/src/driver/tps6699x.rs
- type-c-service/src/service/mod.rs
- type-c-service/src/service/port.rs
- type-c-service/src/wrapper/cfu.rs
- type-c-service/src/wrapper/message.rs
- type-c-service/src/wrapper/mod.rs
- type-c-service/src/wrapper/pd.rs
- type-c-service/src/wrapper/power.rs
This PR refactors the wrapper event loop into its final form. This consists of several parts:
* Move register reads out of `wait_next`. This function currently reads the port status and other data, but this makes it impossible for external code to implement custom behavior immediately after an interrupt is received. Instead of producing events like `(port id, event, data)`, events are now of the form `(port id, event)`. 
* Break up the current `process_event` into `process_event` and `finalize`. `process_event` is now responsible for reading additional data from the PD controller. This break-up allows external code to still access the data for these events. The `finalize` stage is now responsible for sending response to deferred requests and committing any cached state.
* Simplify …
> type-c-service/wrapper: Migrate event loop over to wait/process/finalize

- type-c-service/src/service/ucsi.rs
The OPM polls the CCI to determine when a reset is completep
> type-c-service/ucsi: Don't notify on reset

- embedded-service/src/type_c/controller.rs
- type-c-service/src/driver/tps6699x.rs
- type-c-service/src/wrapper/mod.rs
The wrapper generates a software interrupt as part of `sync_state` but this interrupt was not being cleared.
> type-c-service/wrapper: Clear software interrupt

- Cargo.lock
- embedded-service/src/type_c/controller.rs
- examples/rt685s-evk/Cargo.lock
- examples/std/Cargo.lock
- examples/std/src/lib/type_c/mock_controller.rs
- type-c-service/Cargo.toml
- type-c-service/src/driver/tps6699x.rs
Only async functions that had a positive effect on code size were flattened.
> type-c-service/tps6699x: Remove redundant mutexes and flatten async

- examples/rt685s-evk/src/bin/type_c.rs
- examples/rt685s-evk/src/bin/type_c_cfu.rs
- examples/std/src/bin/type_c/external.rs
- examples/std/src/bin/type_c/service.rs
- examples/std/src/bin/type_c/unconstrained.rs
- examples/std/src/lib/type_c/mock_controller.rs
- type-c-service/src/driver/tps6699x.rs
- type-c-service/src/wrapper/backing.rs
- type-c-service/src/wrapper/cfu.rs
- type-c-service/src/wrapper/dp.rs
- type-c-service/src/wrapper/mod.rs
- type-c-service/src/wrapper/pd.rs
- type-c-service/src/wrapper/power.rs
- type-c-service/src/wrapper/vdm.rs
This PR refactors the backing for the controller wrapper with the goal of removing port count generic arguments. The existing backing types that were used to supply certain data structures have been expanded to also include all needed mutable state and service registration objects. This also helps to simplify constructing wrappers a bit. This PR introduces the types `Storage`, `ReferencedStorage`, and `Backing` to accomplish this task. This PR also introduces a `DynPortState` trait that is used to erase the port count generic from the wrapper.
Since the wrapper no longer has to be monomorphized per port count this results in a size reduction of at least ~14K per monomorphized copy removed.
This PR also includes some general clean-up, most notable is that the wrapper now accepts a `M: …
> type-c-service/wrapper: Remove port count generics

- Cargo.lock
- embedded-service/src/type_c/controller.rs
- examples/rt633/Cargo.lock
- examples/rt685s-evk/Cargo.lock
- examples/std/Cargo.lock
- examples/std/src/bin/type_c/basic.rs
- examples/std/src/bin/type_c/ucsi.rs
- examples/std/src/lib/type_c/mock_controller.rs
- type-c-service/src/driver/tps6699x.rs
- type-c-service/src/service/config.rs
- type-c-service/src/service/ucsi.rs
- type-c-service/src/wrapper/pd.rs
Breaking change due to the new trait function.
Depends on:
> type-c-service: Thread UCSI port commands to hardware

- hid-service/src/i2c/device.rs
**hid-service/src/i2c/device.rs**
In `read_report_descriptor()` moved `let desc = self.get_hid_descriptor().await?;` to occur before borrowing `self.buffer`.
Purpose: eliminate borrow-across-await hazard (avoids holding a mutable borrow while awaiting), fixing a safety/runtime issue.
> move get hid descriptor before borrowing
